// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpH0OWdrDIHtIqU7Bpx1oFN1Xwoxr6w0',
    appId: '1:980816133797:web:3acce43ec7deb9efe0574c',
    messagingSenderId: '980816133797',
    projectId: 'aurion-app-5242e',
    authDomain: 'aurion-app-5242e.firebaseapp.com',
    storageBucket: 'aurion-app-5242e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1OeB5Pxx_i3tUuuyrgJaW7h9irGh9bk',
    appId: '1:980816133797:android:604ca0de3cf904c8e0574c',
    messagingSenderId: '980816133797',
    projectId: 'aurion-app-5242e',
    storageBucket: 'aurion-app-5242e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrYXzIXcRg4hfe5Cap6RJEuhI7M18L9Pk',
    appId: '1:980816133797:ios:482196bafa627d6fe0574c',
    messagingSenderId: '980816133797',
    projectId: 'aurion-app-5242e',
    storageBucket: 'aurion-app-5242e.firebasestorage.app',
    iosBundleId: 'com.example.aurionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrYXzIXcRg4hfe5Cap6RJEuhI7M18L9Pk',
    appId: '1:980816133797:ios:482196bafa627d6fe0574c',
    messagingSenderId: '980816133797',
    projectId: 'aurion-app-5242e',
    storageBucket: 'aurion-app-5242e.firebasestorage.app',
    iosBundleId: 'com.example.aurionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXpH0OWdrDIHtIqU7Bpx1oFN1Xwoxr6w0',
    appId: '1:980816133797:web:af6f944d62a9a539e0574c',
    messagingSenderId: '980816133797',
    projectId: 'aurion-app-5242e',
    authDomain: 'aurion-app-5242e.firebaseapp.com',
    storageBucket: 'aurion-app-5242e.firebasestorage.app',
  );
}
